### ISSUE TITLE
update the ip only if changed

### ISSUE THREAD

**Issue by piermark** [TimLChan/surfshark-smartdns-updater#2]
is possible check the personal IP address and run script update only if IP is changed?
thank

**Comment by piermark** [comment]
#!/bin/sh

CHECKFILE="/tmp/checkMyPublicIPAddress.dat"
OLD_PUBLIC_IP_ADDRESS=""
NEW_PUBLIC_IP_ADDRESS=""

if [[ -f "$CHECKFILE" ]]; then
        OLD_PUBLIC_IP_ADDRESS="`head -n 1 $CHECKFILE`"
fi

NEW_PUBLIC_IP_ADDRESS=`curl 'https://api.ipify.org'`


if [[ "$OLD_PUBLIC_IP_ADDRESS" != "$NEW_PUBLIC_IP_ADDRESS" ]]; then
        echo $NEW_PUBLIC_IP_ADDRESS | tee $CHECKFILE
/bin/sh /root/surfshark.sh

fi

exit 0

**Comment by TimLChan** [comment]
So sorry I just got around to this, thanks for the code snippet above, I've integrated it into the bash script itself so there isn't a need to have a script to run another script 😄
